# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               KCavagnolo
tagline:             The un-blog
url:                 http://kacavgnolo.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ken Cavagnolo
  url:               https://twitter.com/kcavagnolo
  email:             ken@kcavagnolo.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/kcavagnolo/kcavagnolo.github.io
