# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               KCavagnolo
url:                 http://kcavagnolo.com
baseurl:	     "blog"
paginate:            1

# Pages
pages_list:
  About: '/#about_anchor'
  Archive: '/archive'
  Feed: '/atom.xml'

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ken Cavagnolo
  url:               https://twitter.com/kencavagnolo
  email:             ken@kcavagnolo.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/kcavagnolo/kcavagnolo.github.io
