# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:               KCavagnolo
url:                 http://kcavagnolo.com
baseurl:	     ""
blogdir:	     "blog/"
paginate:            1
paginate_path:	     "blog/posts/:num"

# Pages
pages_list:
  Archive: '/archive'
  Feed: '/atom.xml'

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ken Cavagnolo
  url:               https://twitter.com/kencavagnolo
  email:             ken@kcavagnolo.com
