# _config.yml
# Site settings
title: "Ken Cavagnolo"
name: "Ken Cavagnolo"
tagline: "Ken Cavagnolo is a human first."
description: "Ken Cavagnolo is a human first."
email: "nope@nope"
url: "https://www.kcavagnolo.com"
repository: "kcavagnolo/kcavagnolo.github.io"
baseurl: ""
timezone: "America/Los_Angeles"
lang: "en-US"
permalink: pretty

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge

# Build options
safe: true
future: true

# Directories to include (process these even if they start with underscores)
include:
  - public
  - fonts
  - img
  - content

# Directories and files to exclude
exclude:
  - node_modules
  - gulpfile.js
  - gulpfile_example.js
  - README.md
  - svg
  - .idea

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# GitHub metadata (for use with jekyll-github-metadata)
github:
  is_project_page: false
